// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sd3
NumericVector sd3(SEXP v, bool na_rm);
RcppExport SEXP fromo_sd3(SEXP vSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type v(vSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    __result = Rcpp::wrap(sd3(v, na_rm));
    return __result;
END_RCPP
}
// skew4
NumericVector skew4(NumericVector v, bool na_rm);
RcppExport SEXP fromo_skew4(SEXP vSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    __result = Rcpp::wrap(skew4(v, na_rm));
    return __result;
END_RCPP
}
// kurt5
NumericVector kurt5(NumericVector v, bool na_rm);
RcppExport SEXP fromo_kurt5(SEXP vSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    __result = Rcpp::wrap(kurt5(v, na_rm));
    return __result;
END_RCPP
}
