# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' Compute first K moments
#' @description
#' Compute the (standardized) 2nd through kth moments, the mean, and the number of elements.
#' 
#' @param v a vector
#' @param na_rm whether to remove NA, false by default.
#'
#' @details
#'
#' Computes the number of elements, the mean, and the 2nd through kth
#' centered standardized moment, for \eqn{k=2,3,4}{k=2,3,4}. These
#' are computed via the numerically robust one-pass method of Bennett \emph{et. al.}
#' In general they will \emph{not} match exactly with the 'standard'
#' implementations, due to differences in roundoff.
#'
#' These methods are reasonably fast, on par with the 'standard' implementations.
#' However, they will usually be faster than calling the various standard implementations
#' more than once.
#'
#' @return a vector; the first elements are the kth, k-1th through 2nd standardized, centered moment,
#' then the mean, then the number of (non-nan) elements in the input.
#'
#' @note
#' the kurtosis is \emph{excess kurtosis}, with a 3 subtracted, and should be nearly zero
#' for Gaussian input.
#'
#' @examples
#' x <- rnorm(1e5)
#' sd3(x)[1] - sd(x)
#'   skew4(x)[4] - length(x)
#'   skew4(x)[3] - mean(x)
#'   skew4(x)[2] - sd(x)
#' if (require(moments)) {
#'   skew4(x)[1] - skewness(x)
#' }
#' # check 'robustness'; only the mean should change:
#' kurt5(x + 1e12) - kurt5(x)
#' # check speed
#' if (require(microbenchmark) && require(moments)) {
#'   dumbk <- function(x) { c(kurtosis(x) - 3.0,skewness(x),sd(x),mean(x),length(x)) }
#'   set.seed(1234)
#'   x <- rnorm(1e6)
#'   print(kurt5(x) - dumbk(x))
#'   microbenchmark(dumbk(x),kurt5(x),times=10L)
#' }
#'
#' @template etc
#' @template ref-romo
#' @rdname firstmoments
#' @export
sd3 <- function(v, na_rm = FALSE) {
    .Call('fromo_sd3', PACKAGE = 'fromo', v, na_rm)
}

#' @rdname firstmoments
#' @export
skew4 <- function(v, na_rm = FALSE) {
    .Call('fromo_skew4', PACKAGE = 'fromo', v, na_rm)
}

#' @rdname firstmoments
#' @export
kurt5 <- function(v, na_rm = FALSE) {
    .Call('fromo_kurt5', PACKAGE = 'fromo', v, na_rm)
}

